# Generated by Django 4.2.7 on 2025-06-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_id", models.CharField(max_length=20)),
                ("date", models.DateField(blank=True, null=True)),
                ("place", models.CharField(max_length=100)),
                ("distance", models.IntegerField()),
                ("horse_name", models.CharField(max_length=100)),
                ("jockey", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
                ("time", models.FloatField(blank=True, null=True)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("odds", models.FloatField(blank=True, null=True)),
                ("trainer", models.CharField(blank=True, max_length=100, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
