# Generated by Django 4.2.7 on 2025-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceresult",
            name="horse_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="raceresult",
            unique_together={("race_id", "horse_number")},
        ),
    ]
