# Generated by Django 4.2.7 on 2025-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0002_raceresult_horse_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceresult",
            name="distance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
