# Generated by Django 4.2.7 on 2025-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0003_alter_raceresult_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceresult",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
